### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by FelixWeichselgartner** [CiaccoDavide/Unity-UI-Polygon#3]
Hi,

would be nice if you could add a license (preferably MIT), so I can actually use your awesome project.

Have a nice day!
Felix

**Comment by CiaccoDavide** [comment]
Here you go! ;)

**Comment by FelixWeichselgartner** [comment]
Wow. You are fast ^^. TY very much.

**Comment by CiaccoDavide** [comment]
I still have issues from years ago, but this one was easy...

One day I'll fix them, I promise!
